"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import type { CSSProperties } from "react";
import { addWeeks, format, isToday, parseISO, startOfWeek } from "date-fns";
import { CalendarDays, Check, ChevronLeft, ChevronRight, GripVertical, Plus, X } from "lucide-react";
import { confirmTaskCompletion, createTask, deleteTask, setTaskWorkflow, toggleTask, updateTask, type ActionResult } from "@/src/app/today/actions";
import type { TodayTask, TaskCategory, TaskStatus } from "@/src/lib/today";
import type { WeekData } from "@/src/lib/week";

const categories: TaskCategory[] = ["career", "content", "other"];
const categoryLabels: Record<TaskCategory, string> = { career: "Career", content: "Content", other: "Personal" };
const workflow: { status: TaskStatus; label: string }[] = [{ status: "not_started", label: "Upcoming" }, { status: "in_progress", label: "Doing" }, { status: "on_hold", label: "On Hold" }, { status: "done", label: "Done" }];
const inputClass = "w-full rounded-xl border border-border bg-background/65 px-3 py-2.5 text-sm outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/15";
const quietButton = "inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-border bg-card/70 px-3.5 text-sm text-muted-foreground shadow-sm transition hover:bg-muted hover:text-foreground";
type Runner = (key: string, action: (form: FormData) => Promise<ActionResult>, form: FormData, success?: () => void) => Promise<void>;

export function WeekView({ data }: { data: WeekData }) {
  const [view, setView] = useState<"checklist" | "board">("checklist"); const [composer, setComposer] = useState(false); const [editing, setEditing] = useState<number | null>(null); const [pending, setPending] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const thisWeek = data.weekStart === format(startOfWeek(new Date(), { weekStartsOn: 1 }), "yyyy-MM-dd");
  const active = useMemo(() => [...data.overdue, ...data.anytime, ...data.days.flatMap(day => day.tasks)].filter(task => task.status !== "completed"), [data]);
  async function run(key: string, action: (form: FormData) => Promise<ActionResult>, form: FormData, success?: () => void) { setPending(key); setMessage(null); const result = await action(form); setPending(null); if (result.ok) success?.(); else setMessage(result.error); }
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-muted-foreground">{format(parseISO(data.weekStart), "MMMM d")} – {format(parseISO(data.weekEnd), "MMMM d, yyyy")}</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.055em] sm:text-4xl">{thisWeek ? "This Week" : "Week plan"}</h1></div><div className="flex flex-wrap items-center gap-1.5"><button onClick={() => setComposer(true)} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[var(--orange)] px-4 text-sm font-semibold text-white shadow-[0_8px_18px_rgba(190,82,37,.22)]"><Plus size={16} /> Add task</button><Link href={`/week?week=${format(addWeeks(parseISO(data.weekStart), -1), "yyyy-MM-dd")}`} className={quietButton}><ChevronLeft size={16} /></Link><Link href="/week" className={`${quietButton} ${thisWeek ? "border-[var(--orange)] bg-[var(--orange)] text-white" : ""}`}><CalendarDays size={15} /> This week</Link><Link href={`/week?week=${format(addWeeks(parseISO(data.weekStart), 1), "yyyy-MM-dd")}`} className={quietButton}><ChevronRight size={16} /></Link></div></header>{composer && <Composer weekStart={data.weekStart} days={data.days.map(day => day.date)} pending={pending === "create"} onSubmit={form => run("create", createTask, form, () => setComposer(false))} onClose={() => setComposer(false)} />}{message && <div role="status" className="flex justify-between rounded-xl border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-800"><span>{message}</span><button onClick={() => setMessage(null)}><X size={15} /></button></div>}<div className="flex w-fit gap-1 rounded-xl border border-border bg-card/70 p-1"><button onClick={() => setView("checklist")} className={`rounded-lg px-3 py-1.5 text-sm ${view === "checklist" ? "bg-accent font-medium text-accent-foreground" : "text-muted-foreground"}`}>Checklist</button><button onClick={() => setView("board")} className={`rounded-lg px-3 py-1.5 text-sm ${view === "board" ? "bg-accent font-medium text-accent-foreground" : "text-muted-foreground"}`}>Kanban</button></div><div key={view} className="week-view-switch">{view === "checklist" ? <Checklist data={data} editing={editing} setEditing={setEditing} pending={pending} run={run} /> : <Board tasks={active} pending={pending} run={run} />}</div></div>;
}

function Composer({ weekStart, days, pending, onSubmit, onClose }: { weekStart: string; days: string[]; pending: boolean; onSubmit: (form: FormData) => Promise<void>; onClose: () => void }) {
  const [placement, setPlacement] = useState(`anytime:${weekStart}`); const [category, setCategory] = useState<TaskCategory>("career"); const [closing, setClosing] = useState(false); const [mounted, setMounted] = useState(false); const anytime = placement.startsWith("anytime:");
  useEffect(() => { setMounted(true); const previousBodyOverflow = document.body.style.overflow; const previousRootOverflow = document.documentElement.style.overflow; document.body.style.overflow = "hidden"; document.documentElement.style.overflow = "hidden"; return () => { document.body.style.overflow = previousBodyOverflow; document.documentElement.style.overflow = previousRootOverflow; }; }, []);
  function close() { setClosing(true); setTimeout(onClose, 220); }
  if (!mounted) return null;
  return createPortal(<div className={`modal-backdrop ${closing ? "modal-closing" : ""}`} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><form action={onSubmit} className="task-composer" role="dialog" aria-modal="true" aria-labelledby="add-task-title"><div className="flex items-center justify-between"><div><h2 id="add-task-title" className="font-semibold">Add a task</h2><p className="text-xs text-muted-foreground">Choose a day, or keep it flexible for this week.</p></div><button type="button" onClick={close} aria-label="Close add task"><X size={16} /></button></div><input name="title" className={`${inputClass} mt-4`} placeholder="What needs doing?" autoFocus required /><p className="mt-4 mb-2 text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">When</p><div className="choice-grid"><button type="button" onClick={() => setPlacement(`anytime:${weekStart}`)} className={anytime ? "choice-chip choice-chip-active" : "choice-chip"}>Anytime</button>{days.map(date => <button type="button" key={date} onClick={() => setPlacement(date)} className={placement === date ? "choice-chip choice-chip-active" : "choice-chip"}>{format(parseISO(date), "EEE d")}</button>)}</div><p className="mt-4 mb-2 text-xs font-semibold uppercase tracking-[.12em] text-muted-foreground">Category</p><div className="choice-grid choice-grid-compact">{categories.map(value => <button type="button" key={value} onClick={() => setCategory(value)} className={category === value ? "choice-chip choice-chip-active" : "choice-chip"}>{categoryLabels[value]}</button>)}</div><input type="hidden" name="date" value={anytime ? weekStart : placement} /><input type="hidden" name="anytimeWeekStart" value={anytime ? weekStart : ""} /><input type="hidden" name="category" value={category} /><input type="hidden" name="priority" value="normal" /><input type="hidden" name="description" value="" /><input type="hidden" name="estimatedMinutes" value="" /><div className="mt-4 flex justify-end gap-2"><button type="button" className={quietButton} onClick={close}>Cancel</button><button disabled={pending} className="rounded-xl bg-[var(--orange)] px-4 py-2.5 text-sm font-semibold text-white">{pending ? "Adding…" : "Add task"}</button></div></form></div>, document.body);
}

function Checklist({ data, editing, setEditing, pending, run }: { data: WeekData; editing: number | null; setEditing: (value: number | null) => void; pending: string | null; run: Runner }) { return <div className="space-y-4">{data.overdue.length > 0 && <section className="rounded-[22px] border border-amber-500/25 bg-card p-4"><h2 className="text-sm font-semibold">Overdue <span className="font-normal text-muted-foreground">— bring these forward</span></h2><div className="mt-3 space-y-2">{data.overdue.map(task => <TaskCard key={task.id} task={task} overdue pending={pending} run={run} editing={editing === task.id} setEditing={setEditing} />)}</div></section>}<section className="week-anytime-card"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Anytime this week</h2><p className="text-xs text-muted-foreground">Flexible work, ready when you are.</p></div><span className="text-xs text-muted-foreground">{data.anytime.length} tasks</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{data.anytime.length ? data.anytime.map(task => <TaskCard key={task.id} task={task} pending={pending} run={run} editing={editing === task.id} setEditing={setEditing} />) : <p className="text-sm text-muted-foreground">No flexible tasks yet.</p>}</div></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.days.map(({ date, tasks }, index) => <DayCard key={date} date={date} tasks={tasks} glow={index % 2 === 0} sunday={index === 6} editing={editing} setEditing={setEditing} pending={pending} run={run} />)}</div></div>; }
function DayCard({ date, tasks, glow, sunday, editing, setEditing, pending, run }: { date: string; tasks: TodayTask[]; glow: boolean; sunday: boolean; editing: number | null; setEditing: (value: number | null) => void; pending: string | null; run: Runner }) { const completed = tasks.filter(task => task.status === "completed").length; const progress = tasks.length ? Math.round(completed / tasks.length * 100) : 0; return <section className={`week-day-card ${glow ? "week-glow-card" : ""} ${sunday ? "week-sunday-card" : ""}`}><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-[-.03em]">{format(parseISO(date), "EEEE")}{isToday(parseISO(date)) && <span className="ml-2 text-xs font-semibold text-[var(--orange)]">Today</span>}</h2><p className="text-xs text-muted-foreground">{format(parseISO(date), "MMMM d")}{sunday && " · a softer landing"}</p></div><ProgressRing value={progress} completed={completed} total={tasks.length} /></div><div className={`mt-4 space-y-2 ${sunday ? "xl:grid xl:grid-cols-2 xl:gap-2 xl:space-y-0" : ""}`}>{tasks.length ? tasks.map(task => <TaskCard key={task.id} task={task} pending={pending} run={run} editing={editing === task.id} setEditing={setEditing} />) : <div className="rounded-2xl border border-dashed border-border px-3 py-5 text-sm text-muted-foreground">{sunday ? "Keep the day open. Rest is part of the plan." : "Clear day."}</div>}</div></section>; }
function ProgressRing({ value, completed, total }: { value: number; completed: number; total: number }) { const [progress, setProgress] = useState(0); useEffect(() => { const timer = setTimeout(() => setProgress(value), 50); return () => clearTimeout(timer); }, [value]); return <div className="progress-ring" style={{ "--ring-progress": progress / 100 } as CSSProperties}><div>{completed}/{total}</div></div>; }
function TaskCard({ task, overdue, pending, run, editing, setEditing }: { task: TodayTask; overdue?: boolean; pending: string | null; run: Runner; editing: boolean; setEditing: (value: number | null) => void }) {
  const completed = task.status === "completed";
  const [visualCompleted, setVisualCompleted] = useState(completed);
  const [checkAnimation, setCheckAnimation] = useState<"complete" | "reopen" | null>(null);
  useEffect(() => setVisualCompleted(completed), [completed]);
  useEffect(() => {
    if (!checkAnimation) return;
    const timer = window.setTimeout(() => setCheckAnimation(null), 360);
    return () => window.clearTimeout(timer);
  }, [checkAnimation]);
  function toggle(form: FormData) {
    const nextCompleted = !visualCompleted;
    setVisualCompleted(nextCompleted);
    setCheckAnimation(nextCompleted ? "complete" : "reopen");
    run(`toggle-${task.id}`, toggleTask, form);
  }
  const animationClass = checkAnimation ? `week-task-checking-${checkAnimation}` : "";
  const checkAnimationClass = checkAnimation ? `task-check-animate-${checkAnimation}` : "";
  return <article className={`week-task-card ${visualCompleted ? "week-task-completed" : ""} ${animationClass}`}><div className="flex gap-3"><form action={toggle}><input type="hidden" name="id" value={task.id} /><button disabled={pending === `toggle-${task.id}`} aria-label={visualCompleted ? `Reopen ${task.title}` : `Mark ${task.title} complete`} className={`task-check ${visualCompleted ? "task-check-completed" : ""} ${checkAnimationClass}`}>{visualCompleted ? <Check size={12} strokeWidth={3} /> : null}</button></form><div className="min-w-0 flex-1"><p className="text-sm font-medium leading-5">{task.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{categoryLabels[task.category]}{overdue && <> · Overdue from {format(parseISO(task.date), "MMM d")}</>}</p></div><button onClick={() => setEditing(editing ? null : task.id)} className="p-1 text-muted-foreground">•••</button></div>{editing && <EditForm task={task} pending={pending === `update-${task.id}`} onSave={form => run(`update-${task.id}`, updateTask, form, () => setEditing(null))} onDelete={form => run(`delete-${task.id}`, deleteTask, form, () => setEditing(null))} onClose={() => setEditing(null)} />}</article>;
}
function Board({ tasks, pending, run }: { tasks: TodayTask[]; pending: string | null; run: Runner }) { const [dragId, setDragId] = useState<number | null>(null); function drop(status: TaskStatus) { if (!dragId) return; const form = new FormData(); form.set("id", String(dragId)); form.set("status", status); run(`workflow-${dragId}`, setTaskWorkflow, form); setDragId(null); } return <div className="grid gap-4 xl:grid-cols-4">{workflow.map(column => <section key={column.status} onDragOver={event => event.preventDefault()} onDrop={() => drop(column.status)} className="kanban-column"><h2 className="px-1 pb-3 text-sm font-semibold">{column.label} <span className="text-muted-foreground">{tasks.filter(task => task.status === column.status).length}</span></h2><div className="space-y-2">{tasks.filter(task => task.status === column.status).map(task => <article draggable onDragStart={() => setDragId(task.id)} key={task.id} className="kanban-card"><div className="flex gap-2"><GripVertical size={16} className="mt-0.5 shrink-0 text-muted-foreground" /><div><p className="text-sm font-semibold">{task.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{categoryLabels[task.category]} · {format(parseISO(task.date), "MMM d")}</p></div></div>{column.status === "done" ? <form className="mt-3" action={form => run(`confirm-${task.id}`, confirmTaskCompletion, form)}><input type="hidden" name="id" value={task.id} /><button disabled={pending === `confirm-${task.id}`} className="w-full rounded-xl bg-[var(--orange)] px-3 py-2 text-xs font-semibold text-white">Confirm complete</button></form> : <StatusSelect task={task} pending={pending} run={run} />}</article>)}</div></section>)}</div>; }
function StatusSelect({ task, pending, run }: { task: TodayTask; pending: string | null; run: Runner }) { return <form className="mt-3" action={form => run(`workflow-${task.id}`, setTaskWorkflow, form)}><input type="hidden" name="id" value={task.id} /><select name="status" defaultValue={task.status} onChange={event => event.currentTarget.form?.requestSubmit()} disabled={pending === `workflow-${task.id}`} className="w-full rounded-xl border border-border bg-card px-2 py-1.5 text-xs text-muted-foreground"><option value="not_started">Upcoming</option><option value="in_progress">Doing</option><option value="on_hold">On hold</option><option value="done">Done</option></select></form>; }
function EditForm({ task, pending, onSave, onDelete, onClose }: { task: TodayTask; pending: boolean; onSave: (form: FormData) => Promise<void>; onDelete: (form: FormData) => Promise<void>; onClose: () => void }) { return <form action={onSave} className="mt-3 border-t border-border pt-3"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="anytimeWeekStart" value={task.anytimeWeekStart ?? ""} /><input className={inputClass} name="title" defaultValue={task.title} required /><div className="mt-2 grid grid-cols-2 gap-2"><input className={inputClass} name="date" type="date" defaultValue={task.date} required /><select className={inputClass} name="category" defaultValue={task.category}>{categories.map(category => <option key={category} value={category}>{categoryLabels[category]}</option>)}</select></div><input type="hidden" name="priority" value={task.priority} /><input type="hidden" name="description" value={task.description ?? ""} /><input type="hidden" name="estimatedMinutes" value={task.estimatedMinutes ?? ""} /><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={onClose} className="text-sm text-muted-foreground">Cancel</button><button disabled={pending} className="rounded-lg bg-[var(--orange)] px-3 py-1.5 text-sm font-medium text-white">Save</button><button type="button" onClick={() => { if (confirm("Delete this task?")) { const form = new FormData(); form.set("id", String(task.id)); onDelete(form); } }} className="text-sm text-rose-700">Delete</button></div></form>; }
